export const container: string;
export const note: string;
export const textarea: string;
export const formTips: string;
export const formAction: string;
export const passwordWrapper: string;
export const passwordShowHide: string;
export const outputWrapper: string;
export const outputCopyClipboard: string;
